name: Publish (Development)

on:
  push:
    branches:
    - main

jobs:
  publish_to_backend:
    name: "Publish to Backend"

    runs-on: [self-hosted, linux]

    steps:
    - name: checkout engine without LFS
      uses: actions/checkout@v4
      with:
        lfs: true
        token: ${{ secrets.BUMP_ENGINE_GITHUB_TOKEN }}
    - name: Pull ProjectSystem docker image
      run: docker pull ghcr.io/nginetechnologies/projectsystem-dev:latest
    - name: Publish to backend
      run: |
        docker run \
          -v ${{ github.workspace }}:/repo \  # Mount the repo to /repo inside the container
          ghcr.io/nginetechnologies/projectsystem-dev:latest \
          +register_backend_assets /repo/Assets.nassetdb